### ISSUE TITLE
how can i process the response?

### ISSUE THREAD

**Issue by HeroadZ** [vilic/ruff-home#2]
I get a cross domain problem, so I want to set a header to response like
```
Access-Control-Allow-Origin: *
```

I write the code: 
```
server.get('/led-g-off', function(req,response) {
    $('#led-g').turnOff();
    // return {
    //     status: 'Ok'
    // }
    return response;
});
```

you say that 

> If you want to handle the response yourself, you can either process the res object directly (following req parameter) 

but I don't understand how to process it.

thanks if you solve it.

**Comment by vilicvane** [comment]
Hi, you can `res.setHeader('Access-Control-Allow-Origin', '*');` before return `{ status: 'ok' }`.

**Comment by HeroadZ** [comment]
thanks a lot! Maybe I should read the nodejs API first.
